// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippingRecorder.Data;

#nullable disable

namespace ShippingRecorder.Data.Migrations
{
    [DbContext(typeof(ShippingRecorderDbContext))]
    [Migration("20251207050413_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("COUNTRY", null, t =>
                        {
                            t.HasCheckConstraint("CK_Code_Characters", "code GLOB '[A-Z0-9]*'");

                            t.HasCheckConstraint("CK_Code_Length", "length(code) = 2");
                        });
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LOCATION", (string)null);
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Operator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OPERATOR", (string)null);
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Port", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<long>("CountryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("PORT", null, t =>
                        {
                            t.HasCheckConstraint("CK_Code_AlphaNumeric", "code GLOB '[A-Za-z0-9]*'");

                            t.HasCheckConstraint("CK_Code_Length", "length(code) = 5");
                        });
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.RegistrationHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("Cabins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cabins");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("callsign");

                    b.Property<int?>("Crew")
                        .HasColumnType("INTEGER")
                        .HasColumnName("crew");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME")
                        .HasColumnName("date");

                    b.Property<int?>("Decks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("decks");

                    b.Property<long>("FlagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("flag_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("MMSI")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT")
                        .HasColumnName("mmsi");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("OperatorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("operator_id");

                    b.Property<int?>("Passengers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("passengers");

                    b.Property<int?>("Tonnage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tonnage");

                    b.Property<long>("VesselId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vessel_id");

                    b.Property<long>("VesselTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vessel_type_id");

                    b.HasKey("Id");

                    b.HasIndex("FlagId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("VesselId");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("REGISTRATION_HISTORY", null, t =>
                        {
                            t.HasCheckConstraint("CK_Callsign_Characters", "callsign GLOB '[A-Z0-9]*'");

                            t.HasCheckConstraint("CK_MMSI_Length", "length(mmsi) = 9");

                            t.HasCheckConstraint("CK_MMSI_Numeric", "mmsi GLOB '[0-9]*'");
                        });
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Sighting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME")
                        .HasColumnName("date");

                    b.Property<bool>("IsMyVoyage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_my_voyage");

                    b.Property<long>("LocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("location_id");

                    b.Property<long>("VesselId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vessel_id");

                    b.Property<long?>("VoyageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voyage_id");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("VesselId");

                    b.HasIndex("VoyageId");

                    b.ToTable("SIGHTING", (string)null);
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Vessel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("Beam")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beam");

                    b.Property<int?>("Built")
                        .HasColumnType("INTEGER")
                        .HasColumnName("built");

                    b.Property<decimal?>("Draught")
                        .HasColumnType("TEXT")
                        .HasColumnName("draught");

                    b.Property<string>("IMO")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("imo");

                    b.Property<int?>("Length")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length");

                    b.HasKey("Id");

                    b.HasIndex("IMO")
                        .IsUnique();

                    b.ToTable("VESSEL", null, t =>
                        {
                            t.HasCheckConstraint("CK_IMO_Length", "length(imo) = 7");

                            t.HasCheckConstraint("CK_IMO_Numeric", "imo GLOB '[0-9]*'");
                        });
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.VesselType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VESSEL_TYPE", (string)null);
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Voyage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("number");

                    b.Property<long>("OperatorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("operator_id");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("VOYAGE", (string)null);
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.VoyageEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME")
                        .HasColumnName("arrival");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_type");

                    b.Property<long>("PortId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port_id");

                    b.Property<long>("VoyageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voyage_id");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.HasIndex("VoyageId");

                    b.ToTable("VOYAGE_EVENT", (string)null);
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Port", b =>
                {
                    b.HasOne("ShippingRecorder.Entities.Db.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.RegistrationHistory", b =>
                {
                    b.HasOne("ShippingRecorder.Entities.Db.Country", "Flag")
                        .WithMany()
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShippingRecorder.Entities.Db.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShippingRecorder.Entities.Db.Vessel", null)
                        .WithMany("RegistrationHistory")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShippingRecorder.Entities.Db.VesselType", "VesselType")
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flag");

                    b.Navigation("Operator");

                    b.Navigation("VesselType");
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Sighting", b =>
                {
                    b.HasOne("ShippingRecorder.Entities.Db.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShippingRecorder.Entities.Db.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShippingRecorder.Entities.Db.Voyage", "Voyage")
                        .WithMany()
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");

                    b.Navigation("Vessel");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Voyage", b =>
                {
                    b.HasOne("ShippingRecorder.Entities.Db.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.VoyageEvent", b =>
                {
                    b.HasOne("ShippingRecorder.Entities.Db.Port", "Port")
                        .WithMany()
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShippingRecorder.Entities.Db.Voyage", null)
                        .WithMany("Events")
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Port");
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Vessel", b =>
                {
                    b.Navigation("RegistrationHistory");
                });

            modelBuilder.Entity("ShippingRecorder.Entities.Db.Voyage", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
