DELETE FROM SIGHTING;
DELETE FROM VOYAGE_EVENT;
DELETE FROM VOYAGE;

DELETE FROM SQLITE_SEQUENCE WHERE name='SIGHTING';
DELETE FROM SQLITE_SEQUENCE WHERE name='VOYAGE_EVENT';
DELETE FROM SQLITE_SEQUENCE WHERE name='VOYAGE';
